#!/bin/bash
sync(){
	touch tab.tmp
	crontab -l > tab.tmp
}
clr(){
	touch tab.tmp
	rm -rf tab.tmp
}
create() {
	echo "Введите имя отслеживаемого процесса"
	read name
	echo "Выберите период проверки (в минутах)"
	read time
	if [[ $(sed -n '$=' tab.tmp) -le 1 ]]
		then
		echo "DISPLAY=:0" > tab.tmp
	fi
    echo "*/$time * * * * bash /home/oleg/scripts/bash/procKeeper/procKeeper $name" >> tab.tmp
    crontab tab.tmp
    show
    clr
}
track(){
	if [[ $(pidof $per) > 1 ]]
		then
		exit
	else
		$per
	fi
}
show(){
	if [[ $(crontab -l | grep procKeeper | wc -l) -eq 0 ]]
	then
		echo "Нет активных отслеживаний"
	else	
		crontab -l | sed -n '/procKeeper/p; =' | sed 'N;s/\n/. /' | sed '$d'
	fi
	}
edit(){
	show
	echo "Выберите отслеживание для удаления"
	read num
	VAR=`crontab -l | sed -n '/procKeeper/p' | sed "${num} !d" | sed 's/^\(.\)/\1\\\/' | cut -c 1-6`
	sed -i "/${VAR}/d" tab.tmp;
	echo "Введите имя отслеживаемого процесса"
	read name
	echo "Выберите период проверки (в минутах)"
	read time
	if [[ $(sed -n '$=' tab.tmp) -le 1 ]]
		then
		echo "DISPLAY=:0" > tab.tmp
	fi
    echo "*/$time * * * * bash /home/oleg/scripts/bash/procKeeper/procKeeper $name" >> tab.tmp
    crontab tab.tmp
    show
    clr
}

remove(){
	show
	echo "Выберите отслеживание для удаления"
	read num
	VAR=`crontab -l | sed -n '/procKeeper/p' | sed "${num} !d" | sed 's/^\(.\)/\1\\\/' | cut -c 1-6`
	sed -i "/${VAR}/d" tab.tmp;
	crontab tab.tmp
	show
	clr
}
per=$1
if [[ $1 == "" ]]
	then
	echo -e "1.Создать\n2.Редактировать\n3.Удалить\n4.Показать"
	read action
	sync
	case $action in
		1)
			create
			;;
		2)
			edit
			;;
		3)
			remove
			;;
		4)
			show
			;;
	esac
else
	track
fi
